### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by torkelhi** [sdushantha/bookingsystem#11]
Vi mangler en navbar som forteller hvilken side man er på og som gir muligheten til å navigere.

Foreslått løsning:
Kan lage en navbar i .inc mappen på grunn av at den skal bli gjenbrukt flere steder.

- require_once("/inc/navbar.php");

**Comment by sdushantha** [comment]
Dette er en veldig bra ide!

Vi burde kanskje også en fil i som har en del basic ting som man må bruker. F.eks bootstrap, ikoner, osv
Fordi da slipper vi å inkludere dem alle manuelt i hver fil.
